version: '3.4'

services:
  equilibriumapp:
    image: equilibriumapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 1000:1000
